[web]
port = 8081

[targets.demo]
type = "http"
HttpUrl = "http://google.fr"
pollingInterval = "5s"

[targets.pingo]
type = "http"
HttpUrl = "http://localhost:8082"
pollingInterval = "5s"

[alerts]
emails = [ "paul@email.com", "john@email.com" ]

[alerts.webhooks.test]
method = "GET"
urlTemplate = "http://test.com/troalall"